import {useState} from 'react';
import {ArrowRight,ShieldCheck,Activity,Newspaper, Bell, BarChart3} from 'lucide-react';
import {login,register} from '../lib/api';

export default function Login({onDone}:{onDone:()=>void}){
 const [mode,setMode]=useState<'login'|'signup'>('login');const [email,setEmail]=useState('demo@watchmegroww.app');const [password,setPassword]=useState('demo1234');const [confirm,setConfirm]=useState('demo1234');const [err,setErr]=useState('');const [busy,setBusy]=useState(false);
 const submit=async()=>{setErr('');if(password.length<6){setErr('Password must be at least 6 characters.');return}if(mode==='signup'&&password!==confirm){setErr('Passwords do not match.');return}setBusy(true);try{mode==='login'?await login(email,password):await register(email,password);onDone()}catch(e:any){setErr(e.message||'Something went wrong')}finally{setBusy(false)}};
 return <main className="auth-shell"><div className="auth-left"><div className="brand-row"><img src="/bear.png" className="brand-bear" onError={e=>{(e.currentTarget as HTMLImageElement).style.display='none'}}/><span>Watch Me <em>Groww</em></span></div><div className="auth-copy"><div className="eyebrow">INDIA-FIRST MARKET INTELLIGENCE</div><h1>Know what moved<br/><span>while you were away.</span></h1><p>Watch Me Groww watches your stocks and the broader market, then turns price, volume, technical signals, verified news and alerts into a concise explanation of what you missed.</p><div className="feature-grid"><div><Activity/><b>What moved</b><small>Since-last-check changes, unusual volume and momentum.</small></div><div><Newspaper/><b>Why it moved</b><small>Verified news and corporate events when available.</small></div><div><Bell/><b>Never miss an alert</b><small>Server-side conditions create persistent notifications.</small></div><div><BarChart3/><b>Compare context</b><small>Market, sector and stock performance in one place.</small></div></div></div><div className="auth-foot"><ShieldCheck size={15}/> Decision support, not financial advice.</div></div><div className="auth-right"><div className="auth-card"><div className="mobile-brand"><img src="/bear.png" onError={e=>{(e.currentTarget as HTMLImageElement).style.display='none'}}/> Watch Me <em>Groww</em></div><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Log in</button><button className={mode==='signup'?'active':''} onClick={()=>setMode('signup')}>Create account</button></div><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p className="muted">{mode==='login'?'Pick up where you left off.':'Your watchlists and alerts are stored server-side, so they follow your account across devices.'}</p><label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email"/><label>Password</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password"/><div className={mode==='signup'?'block':'hidden'}><label>Confirm password</label><input value={confirm} onChange={e=>setConfirm(e.target.value)} type="password"/></div>{err&&<div className="error-box">{err}</div>}<button className="primary-btn w-full mt-5" disabled={busy} onClick={submit}>{busy?'Please wait…':mode==='login'?'Enter Watch Me Groww':'Create account'}<ArrowRight size={17}/></button>{mode==='login'&&<div className="demo-box"><b>Hackathon demo</b><br/>demo@watchmegroww.app<br/>demo1234</div>}<p className="tiny muted">Your market state, watchlists, alerts and “since last checked” baseline are persisted in the database.</p></div></div></main>
}
